#!/usr/bin/expect -f
set timeout 120
set pass "nE315uSK*?t#DQ"
spawn ssh -o StrictHostKeyChecking=no root@147.45.155.163 "curl -s -X POST https://yustex.bitrix24.uz/rest/11/6kuit00wrbcyega9/catalog.productImage.list -H 'Content-Type: application/json' -d '{\"productId\":2703,\"select\":[\"id\",\"name\",\"productId\",\"type\",\"createTime\",\"downloadUrl\",\"detailUrl\"]}'"
expect "*password:*"
send -- "$pass\r"
expect eof
